In [6]:
import pandas as pd 
import numpy as np

In [7]:
m_teams = pd.read_csv('/Users/shaurya/Downloads/MTeams.csv')

In [8]:
m_teams

     TeamID        TeamName  FirstD1Season  LastD1Season
0      1101     Abilene Chr           2014          2026
1      1102       Air Force           1985          2026
2      1103           Akron           1985          2026
3      1104         Alabama           1985          2026
4      1105     Alabama A&M           2000          2026
..      ...             ...            ...           ...
376    1477  East Texas A&M           2023          2026
377    1478        Le Moyne           2024          2026
378    1479      Mercyhurst           2025          2026
379    1480    West Georgia           2025          2026
380    1481       New Haven           2026          2026

[381 rows x 4 columns]

In [9]:
m_teams.isnull().sum()

TeamID           0
TeamName         0
FirstD1Season    0
LastD1Season     0
dtype: int64

In [10]:
w_teams = pd.read_csv('/Users/shaurya/Downloads/WTeams.csv')

In [11]:
w_teams

     TeamID        TeamName
0      3101     Abilene Chr
1      3102       Air Force
2      3103           Akron
3      3104         Alabama
4      3105     Alabama A&M
..      ...             ...
374    3477  East Texas A&M
375    3478        Le Moyne
376    3479      Mercyhurst
377    3480    West Georgia
378    3481       New Haven

[379 rows x 2 columns]

In [12]:
w_teams.isnull().sum()

TeamID      0
TeamName    0
dtype: int64

In [13]:
m_seasons = pd.read_csv('/Users/shaurya/Downloads/MSeasons.csv')

In [14]:
m_seasons

    Season     DayZero      RegionW    RegionX         RegionY       RegionZ
0     1985  10/29/1984         East       West         Midwest     Southeast
1     1986  10/28/1985         East    Midwest       Southeast          West
2     1987  10/27/1986         East  Southeast         Midwest          West
3     1988  11/02/1987         East    Midwest       Southeast          West
4     1989  10/31/1988         East       West         Midwest     Southeast
5     1990  10/30/1989         East    Midwest       Southeast          West
6     1991  10/29/1990         East  Southeast         Midwest          West
7     1992  11/04/1991         East       West         Midwest     Southeast
8     1993  11/02/1992         East    Midwest       Southeast          West
9     1994  11/01/1993         East  Southeast         Midwest          West
10    1995  10/31/1994         East       West         Midwest     Southeast
11    1996  10/30/1995         East    Midwest       Southeast          West
12    1997  10/28/1996         East  Southeast         Midwest          West
13    1998  10/27/1997         East       West         Midwest         South
14    1999  10/26/1998         East    Midwest           South          West
15    2000  11/01/1999         East      South         Midwest          West
16    2001  10/30/2000         East       West         Midwest         South
17    2002  10/29/2001         East    Midwest           South          West
18    2003  11/04/2002         East      South         Midwest          West
19    2004  11/03/2003      Atlanta    Phoenix  EastRutherford       StLouis
20    2005  11/01/2004  Albuquerque    Chicago          Austin      Syracuse
21    2006  10/31/2005      Atlanta    Oakland     Minneapolis  WashingtonDC
22    2007  10/30/2006         East      South         Midwest          West
23    2008  11/05/2007         East    Midwest           South          West
24    2009  11/03/2008         East      South         Midwest          West
25    2010  11/02/2009         East      South         Midwest          West
26    2011  11/01/2010         East       West       Southeast     Southwest
27    2012  10/31/2011         East    Midwest           South          West
28    2013  11/05/2012         East      South         Midwest          West
29    2014  11/04/2013         East      South         Midwest          West
30    2015  11/03/2014         East      South         Midwest          West
31    2016  11/02/2015         East    Midwest           South          West
32    2017  10/31/2016         East       West         Midwest         South
33    2018  10/30/2017         East    Midwest           South          West
34    2019  11/05/2018         East       West         Midwest         South
35    2020  11/04/2019          NA1        NA2             NA3           NA4
36    2021  11/02/2020         East       West         Midwest         South
37    2022  11/01/2021         East       West         Midwest         South
38    2023  10/31/2022         East      South         Midwest          West
39    2024  11/06/2023         East       West         Midwest         South
40    2025  11/04/2024         East    Midwest           South          West
41    2026  11/03/2025         TBD1       TBD2            TBD3          TBD4

In [15]:
m_seasons.isnull().sum()

Season     0
DayZero    0
RegionW    0
RegionX    0
RegionY    0
RegionZ    0
dtype: int64

In [16]:
w_seasons = pd.read_csv('/Users/shaurya/Downloads/WSeasons.csv')

In [17]:
w_seasons

    Season     DayZero      RegionW       RegionX       RegionY       RegionZ
0     1998  10/27/1997         East       Midwest       Mideast          West
1     1999  10/26/1998         East       Mideast       Midwest          West
2     2000  11/01/1999         East       Midwest       Mideast          West
3     2001  10/30/2000         East       Midwest       Mideast          West
4     2002  10/29/2001         East          West       Mideast       Midwest
5     2003  11/04/2002         East          West       Mideast       Midwest
6     2004  11/03/2003         East       Mideast       Midwest          West
7     2005  11/01/2004  Chattanooga         Tempe    KansasCity  Philadelphia
8     2006  10/31/2005  Albuquerque     Cleveland    Bridgeport   San Antonio
9     2007  10/30/2006       Dallas        Dayton        Fresno    Greensboro
10    2008  11/05/2007   Greensboro       Spokane    NewOrleans  OklahomaCity
11    2009  11/03/2008     Berkeley       Trenton  OklahomaCity       Raleigh
12    2010  11/02/2009       Dayton       Memphis    KansasCity    Sacramento
13    2011  11/01/2010       Dallas       Spokane        Dayton  Philadelphia
14    2012  10/31/2011    DesMoines        Fresno      Kingston       Raleigh
15    2013  11/05/2012   Bridgeport       Norfolk  OklahomaCity       Spokane
16    2014  11/04/2013      Lincoln      Stanford    Louisville     NotreDame
17    2015  11/03/2014       Albany       Spokane    Greensboro  OklahomaCity
18    2016  11/02/2015   Bridgeport        Dallas     Lexington    SiouxFalls
19    2017  10/31/2016   Bridgeport  OklahomaCity     Lexington      Stockton
20    2018  10/30/2017       Albany       Spokane    KansasCity     Lexington
21    2019  11/05/2018       Albany       Chicago    Greensboro      Portland
22    2020  11/04/2019          NA1           NA2           NA3           NA4
23    2021  11/02/2020        Alamo     Hemisfair       Mercado     RiverWalk
24    2022  11/01/2021   Bridgeport       Spokane    Greensboro       Wichita
25    2023  10/31/2022  Greenville1      Seattle4   Greenville2      Seattle3
26    2024  11/06/2023      Albany1     Portland4       Albany2     Portland3
27    2025  11/04/2024  Birmingham2   Birmingham3      Spokane1      Spokane4
28    2026  11/03/2025         TBD1          TBD2          TBD3          TBD4

In [18]:
w_seasons.isnull().sum()

Season     0
DayZero    0
RegionW    0
RegionX    0
RegionY    0
RegionZ    0
dtype: int64

In [19]:
m_seeds = pd.read_csv('/Users/shaurya/Downloads/MNCAATourneySeeds.csv')

In [20]:
m_seeds

      Season Seed  TeamID
0       1985  W01    1207
1       1985  W02    1210
2       1985  W03    1228
3       1985  W04    1260
4       1985  W05    1374
...      ...  ...     ...
2689    2026  Z12    1219
2690    2026  Z13    1218
2691    2026  Z14    1244
2692    2026  Z15    1474
2693    2026  Z16    1254

[2694 rows x 3 columns]

In [21]:
m_seeds.isnull().sum()

Season    0
Seed      0
TeamID    0
dtype: int64

In [22]:
w_seeds = pd.read_csv('/Users/shaurya/Downloads/WNCAATourneySeeds.csv')

In [23]:
w_seeds

      Season Seed  TeamID
0       1998  W01    3330
1       1998  W02    3163
2       1998  W03    3112
3       1998  W04    3301
4       1998  W05    3272
...      ...  ...     ...
1807    2026  Z12    3211
1808    2026  Z13    3453
1809    2026  Z14    3158
1810    2026  Z15    3239
1811    2026  Z16    3465

[1812 rows x 3 columns]

In [24]:
w_seeds.isnull().sum()

Season    0
Seed      0
TeamID    0
dtype: int64

In [25]:
m_compact_result = pd.read_csv('/Users/shaurya/Downloads/MRegularSeasonCompactResults.csv')

In [26]:
m_compact_result

        Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0         1985      20     1228      81     1328      64    N      0
1         1985      25     1106      77     1354      70    H      0
2         1985      25     1112      63     1223      56    H      0
3         1985      25     1165      70     1432      54    H      0
4         1985      25     1192      86     1447      74    H      0
...        ...     ...      ...     ...      ...     ...  ...    ...
196818    2026      93     1457      80     1347      78    A      0
196819    2026      93     1459      81     1440      67    A      0
196820    2026      93     1464      90     1236      61    A      0
196821    2026      93     1472      77     1355      62    A      0
196822    2026      93     1477      74     1322      68    A      0

[196823 rows x 8 columns]

In [27]:
m_compact_result.isnull().sum()

Season     0
DayNum     0
WTeamID    0
WScore     0
LTeamID    0
LScore     0
WLoc       0
NumOT      0
dtype: int64

In [28]:
w_compact_result = pd.read_csv('/Users/shaurya/Downloads/WRegularSeasonCompactResults.csv')

In [29]:
w_compact_result

        Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0         1998      18     3104      91     3202      41    H      0
1         1998      18     3163      87     3221      76    H      0
2         1998      18     3222      66     3261      59    H      0
3         1998      18     3307      69     3365      62    H      0
4         1998      18     3349     115     3411      35    H      0
...        ...     ...      ...     ...      ...     ...  ...    ...
140820    2026      93     3421      60     3149      48    A      0
140821    2026      93     3428      67     3416      57    A      0
140822    2026      93     3437      67     3139      57    A      0
140823    2026      93     3452      61     3160      55    A      0
140824    2026      93     3466      55     3122      50    H      0

[140825 rows x 8 columns]

In [30]:
w_compact_result.isnull().sum()

Season     0
DayNum     0
WTeamID    0
WScore     0
LTeamID    0
LScore     0
WLoc       0
NumOT      0
dtype: int64

In [31]:
m_tourney_compact_result = pd.read_csv('/Users/shaurya/Downloads/MNCAATourneyCompactResults.csv')

In [32]:
m_tourney_compact_result

      Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0       1985     136     1116      63     1234      54    N      0
1       1985     136     1120      59     1345      58    N      0
2       1985     136     1207      68     1250      43    N      0
3       1985     136     1229      58     1425      55    N      0
4       1985     136     1242      49     1325      38    N      0
...      ...     ...      ...     ...      ...     ...  ...    ...
2580    2025     146     1120      70     1277      64    N      0
2581    2025     146     1222      69     1397      50    N      0
2582    2025     152     1196      79     1120      73    N      0
2583    2025     152     1222      70     1181      67    N      0
2584    2025     154     1196      65     1222      63    N      0

[2585 rows x 8 columns]

In [33]:
m_tourney_compact_result.isnull().sum()

Season     0
DayNum     0
WTeamID    0
WScore     0
LTeamID    0
LScore     0
WLoc       0
NumOT      0
dtype: int64

In [34]:
w_tourney_compact_result = pd.read_csv('/Users/shaurya/Downloads/WNCAATourneyCompactResults.csv')

In [35]:
w_tourney_compact_result

      Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0       1998     137     3104      94     3422      46    H      0
1       1998     137     3112      75     3365      63    H      0
2       1998     137     3163      93     3193      52    H      0
3       1998     137     3198      59     3266      45    H      0
4       1998     137     3203      74     3208      72    A      0
...      ...     ...      ...     ...      ...     ...  ...    ...
1712    2025     147     3163      78     3425      64    N      0
1713    2025     147     3400      58     3395      47    N      0
1714    2025     151     3163      85     3417      51    N      0
1715    2025     151     3376      74     3400      57    N      0
1716    2025     153     3163      82     3376      59    N      0

[1717 rows x 8 columns]

In [36]:
w_tourney_compact_result.isnull().sum()

Season     0
DayNum     0
WTeamID    0
WScore     0
LTeamID    0
LScore     0
WLoc       0
NumOT      0
dtype: int64

In [37]:
sample_sub_stage1 = pd.read_csv('/Users/shaurya/Downloads/SampleSubmissionStage1.csv')

In [38]:
sample_sub_stage1

                    ID  Pred
0       2022_1101_1102   0.5
1       2022_1101_1103   0.5
2       2022_1101_1104   0.5
3       2022_1101_1105   0.5
4       2022_1101_1106   0.5
...                ...   ...
519139  2025_3477_3479   0.5
519140  2025_3477_3480   0.5
519141  2025_3478_3479   0.5
519142  2025_3478_3480   0.5
519143  2025_3479_3480   0.5

[519144 rows x 2 columns]

In [39]:
sample_sub_stage2 = pd.read_csv('/Users/shaurya/Downloads/SampleSubmissionStage2.csv')

In [40]:
sample_sub_stage2

                    ID  Pred
0       2026_1101_1102   0.5
1       2026_1101_1103   0.5
2       2026_1101_1104   0.5
3       2026_1101_1105   0.5
4       2026_1101_1106   0.5
...                ...   ...
132128  2026_3478_3480   0.5
132129  2026_3478_3481   0.5
132130  2026_3479_3480   0.5
132131  2026_3479_3481   0.5
132132  2026_3480_3481   0.5

[132133 rows x 2 columns]

In [41]:
m_regular_season_detailed = pd.read_csv('/Users/shaurya/Downloads/MRegularSeasonDetailedResults.csv')

In [42]:
m_regular_season_detailed

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124524,2026,132,1335,88,1463,84,N,1,29,64,...,24,13,17,17,24,23,9,9,4,16
124525,2026,132,1345,80,1276,72,N,0,30,57,...,24,5,6,11,22,15,7,2,3,18
124526,2026,132,1378,70,1455,55,N,0,23,61,...,19,13,20,12,27,8,14,7,7,19
124527,2026,132,1433,70,1173,62,N,0,23,57,...,21,9,17,8,31,16,11,3,4,18
124528,2026,132,1465,63,1430,61,A,0,22,58,...,8,14,24,9,24,11,14,6,3,11

In [43]:
m_regular_season_detailed.isnull().sum()

Season     0
DayNum     0
WTeamID    0
WScore     0
LTeamID    0
LScore     0
WLoc       0
NumOT      0
WFGM       0
WFGA       0
WFGM3      0
WFGA3      0
WFTM       0
WFTA       0
WOR        0
WDR        0
WAst       0
WTO        0
WStl       0
WBlk       0
WPF        0
LFGM       0
LFGA       0
LFGM3      0
LFGA3      0
LFTM       0
LFTA       0
LOR        0
LDR        0
LAst       0
LTO        0
LStl       0
LBlk       0
LPF        0
dtype: int64

In [44]:
w_regular_season_detailed = pd.read_csv('/Users/shaurya/Downloads/WRegularSeasonDetailedResults.csv')

In [45]:
w_regular_season_detailed

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2010,11,3103,63,3237,49,H,0,23,54,...,13,6,10,11,27,11,23,7,6,19
1,2010,11,3104,73,3399,68,N,0,26,62,...,21,14,27,14,26,7,20,4,2,27
2,2010,11,3110,71,3224,59,A,0,29,62,...,14,19,23,17,23,8,15,6,0,15
3,2010,11,3111,63,3267,58,A,0,27,52,...,26,16,25,22,22,15,11,14,5,14
4,2010,11,3119,74,3447,70,H,1,30,74,...,17,11,21,21,32,12,14,4,2,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87182,2026,131,3471,60,3218,48,N,0,25,69,...,16,8,8,2,31,9,17,3,6,15
87183,2026,132,3158,68,3220,56,N,0,23,61,...,21,3,5,9,25,10,13,2,4,17
87184,2026,132,3192,79,3254,57,H,0,31,60,...,20,12,14,5,19,2,11,5,4,15
87185,2026,132,3221,77,3250,70,H,0,31,60,...,24,9,12,8,17,17,11,6,2,12
87186,2026,132,3293,91,3191,70,N,0,35,68,...,12,10,15,13,21,9,13,2,4,17

In [46]:
w_regular_season_detailed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87187 entries, 0 to 87186
Data columns (total 34 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Season   87187 non-null  int64
 1   DayNum   87187 non-null  int64
 2   WTeamID  87187 non-null  int64
 3   WScore   87187 non-null  int64
 4   LTeamID  87187 non-null  int64
 5   LScore   87187 non-null  int64
 6   WLoc     87187 non-null  object
 7   NumOT    87187 non-null  int64
 8   WFGM     87187 non-null  int64
 9   WFGA     87187 non-null  int64
 10  WFGM3    87187 non-null  int64
 11  WFGA3    87187 non-null  int64
 12  WFTM     87187 non-null  int64
 13  WFTA     87187 non-null  int64
 14  WOR      87187 non-null  int64
 15  WDR      87187 non-null  int64
 16  WAst     87187 non-null  int64
 17  WTO      87187 non-null  int64
 18  WStl     87187 non-null  int64
 19  WBlk     87187 non-null  int64
 20  WPF      87187 non-null  int64
 21  LFGM     87187 non-null  int64
 22  LFGA     87187 non-null  int64
 23  LFGM3    87187 non-null  int64
 24  LFGA3    87187 non-null  int64
 25  LFTM     87187 non-null  int64
 26  LFTA     87187 non-null  int64
 27  LOR      87187 non-null  int64
 28  LDR      87187 non-null  int64
 29  LAst     87187 non-null  int64
 30  LTO      87187 non-null  int64
 31  LStl     87187 non-null  int64
 32  LBlk     87187 non-null  int64
 33  LPF      87187 non-null  int64
dtypes: int64(33), object(1)
memory usage: 22.6+ MB

In [47]:
m_tourney_detailed_result = pd.read_csv('/Users/shaurya/Downloads/MNCAATourneyDetailedResults.csv')

In [48]:
m_tourney_detailed_result

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,134,1421,92,1411,84,N,1,32,69,...,31,14,31,17,28,16,15,5,0,22
1,2003,136,1112,80,1436,51,N,0,31,66,...,16,7,7,8,26,12,17,10,3,15
2,2003,136,1113,84,1272,71,N,0,31,59,...,28,14,21,20,22,11,12,2,5,18
3,2003,136,1141,79,1166,73,N,0,29,53,...,17,12,17,14,17,20,21,6,6,21
4,2003,136,1143,76,1301,74,N,1,27,64,...,21,15,20,10,26,16,14,5,8,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1444,2025,146,1120,70,1277,64,N,0,26,61,...,23,13,16,13,28,12,9,5,5,18
1445,2025,146,1222,69,1397,50,N,0,28,66,...,29,15,20,12,23,12,9,3,2,9
1446,2025,152,1196,79,1120,73,N,0,25,53,...,25,16,23,9,21,11,14,11,3,22
1447,2025,152,1222,70,1181,67,N,0,23,61,...,17,18,23,10,21,14,7,7,4,16
1448,2025,154,1196,65,1222,63,N,0,21,53,...,25,9,14,15,24,5,9,5,6,19

In [49]:
m_tourney_detailed_result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1449 entries, 0 to 1448
Data columns (total 34 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Season   1449 non-null   int64
 1   DayNum   1449 non-null   int64
 2   WTeamID  1449 non-null   int64
 3   WScore   1449 non-null   int64
 4   LTeamID  1449 non-null   int64
 5   LScore   1449 non-null   int64
 6   WLoc     1449 non-null   object
 7   NumOT    1449 non-null   int64
 8   WFGM     1449 non-null   int64
 9   WFGA     1449 non-null   int64
 10  WFGM3    1449 non-null   int64
 11  WFGA3    1449 non-null   int64
 12  WFTM     1449 non-null   int64
 13  WFTA     1449 non-null   int64
 14  WOR      1449 non-null   int64
 15  WDR      1449 non-null   int64
 16  WAst     1449 non-null   int64
 17  WTO      1449 non-null   int64
 18  WStl     1449 non-null   int64
 19  WBlk     1449 non-null   int64
 20  WPF      1449 non-null   int64
 21  LFGM     1449 non-null   int64
 22  LFGA     1449 non-null   int64
 23  LFGM3    1449 non-null   int64
 24  LFGA3    1449 non-null   int64
 25  LFTM     1449 non-null   int64
 26  LFTA     1449 non-null   int64
 27  LOR      1449 non-null   int64
 28  LDR      1449 non-null   int64
 29  LAst     1449 non-null   int64
 30  LTO      1449 non-null   int64
 31  LStl     1449 non-null   int64
 32  LBlk     1449 non-null   int64
 33  LPF      1449 non-null   int64
dtypes: int64(33), object(1)
memory usage: 385.0+ KB

In [50]:
w_tourney_detailed_result = pd.read_csv('/Users/shaurya/Downloads/WNCAATourneyDetailedResults.csv')

In [51]:
w_tourney_detailed_result

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2010,138,3124,69,3201,55,N,0,28,57,...,34,3,5,17,19,12,18,4,1,18
1,2010,138,3173,67,3395,66,N,0,23,59,...,27,14,15,18,26,8,8,8,6,22
2,2010,138,3181,72,3214,37,H,0,26,57,...,15,3,8,10,21,4,16,6,4,20
3,2010,138,3199,75,3256,61,H,0,25,63,...,20,17,22,16,21,13,16,5,4,24
4,2010,138,3207,62,3265,42,N,0,24,68,...,26,11,17,16,22,9,10,3,4,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
956,2025,147,3163,78,3425,64,N,0,27,60,...,13,23,26,13,29,7,15,8,2,18
957,2025,147,3400,58,3395,47,N,0,24,61,...,20,19,21,11,27,8,21,1,3,14
958,2025,151,3163,85,3417,51,N,0,33,60,...,16,7,8,8,21,11,19,5,2,12
959,2025,151,3376,74,3400,57,N,0,29,57,...,10,9,12,9,20,10,14,6,5,17
960,2025,153,3163,82,3376,59,N,0,30,62,...,16,13,18,17,19,9,11,6,4,17

In [52]:
w_tourney_detailed_result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 961 entries, 0 to 960
Data columns (total 34 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Season   961 non-null    int64
 1   DayNum   961 non-null    int64
 2   WTeamID  961 non-null    int64
 3   WScore   961 non-null    int64
 4   LTeamID  961 non-null    int64
 5   LScore   961 non-null    int64
 6   WLoc     961 non-null    object
 7   NumOT    961 non-null    int64
 8   WFGM     961 non-null    int64
 9   WFGA     961 non-null    int64
 10  WFGM3    961 non-null    int64
 11  WFGA3    961 non-null    int64
 12  WFTM     961 non-null    int64
 13  WFTA     961 non-null    int64
 14  WOR      961 non-null    int64
 15  WDR      961 non-null    int64
 16  WAst     961 non-null    int64
 17  WTO      961 non-null    int64
 18  WStl     961 non-null    int64
 19  WBlk     961 non-null    int64
 20  WPF      961 non-null    int64
 21  LFGM     961 non-null    int64
 22  LFGA     961 non-null    int64
 23  LFGM3    961 non-null    int64
 24  LFGA3    961 non-null    int64
 25  LFTM     961 non-null    int64
 26  LFTA     961 non-null    int64
 27  LOR      961 non-null    int64
 28  LDR      961 non-null    int64
 29  LAst     961 non-null    int64
 30  LTO      961 non-null    int64
 31  LStl     961 non-null    int64
 32  LBlk     961 non-null    int64
 33  LPF      961 non-null    int64
dtypes: int64(33), object(1)
memory usage: 255.4+ KB

In [53]:
cities = pd.read_csv('/Users/shaurya/Downloads/Cities.csv')

In [54]:
cities

     CityID                   City State
0      4001                Abilene    TX
1      4002                  Akron    OH
2      4003                 Albany    NY
3      4004            Albuquerque    NM
4      4005              Allentown    PA
..      ...                    ...   ...
504    4527       Colorado Springs    CO
505    4528                Hershey    PA
506    4529  Charlotte Amalie West    VI
507    4530       Puerto Aventuras    MX
508    4531                 Odessa    TX

[509 rows x 3 columns]

In [55]:
cities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 509 entries, 0 to 508
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CityID  509 non-null    int64
 1   City    509 non-null    object
 2   State   509 non-null    object
dtypes: int64(1), object(2)
memory usage: 12.1+ KB

In [56]:
m_game_cities = pd.read_csv('/Users/shaurya/Downloads/MGameCities.csv')

In [57]:
m_game_cities

       Season  DayNum  WTeamID  LTeamID   CRType  CityID
0        2010       7     1143     1293  Regular    4027
1        2010       7     1314     1198  Regular    4061
2        2010       7     1326     1108  Regular    4080
3        2010       7     1393     1107  Regular    4340
4        2010       9     1143     1178  Regular    4027
...       ...     ...      ...      ...      ...     ...
90679    2026      93     1457     1347  Regular    4286
90680    2026      93     1459     1440  Regular    4194
90681    2026      93     1464     1236  Regular    4124
90682    2026      93     1472     1355  Regular    4046
90683    2026      93     1477     1322  Regular    4234

[90684 rows x 6 columns]

In [58]:
m_game_cities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90684 entries, 0 to 90683
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Season   90684 non-null  int64
 1   DayNum   90684 non-null  int64
 2   WTeamID  90684 non-null  int64
 3   LTeamID  90684 non-null  int64
 4   CRType   90684 non-null  object
 5   CityID   90684 non-null  int64
dtypes: int64(5), object(1)
memory usage: 4.2+ MB

In [59]:
w_game_cities = pd.read_csv('/Users/shaurya/Downloads/WGameCities.csv')

In [60]:
w_game_cities

       Season  DayNum  WTeamID  LTeamID   CRType  CityID
0        2010      11     3103     3237  Regular    4002
1        2010      11     3104     3399  Regular    4085
2        2010      11     3110     3224  Regular    4363
3        2010      11     3111     3267  Regular    4158
4        2010      11     3119     3447  Regular    4367
...       ...     ...      ...      ...      ...     ...
87348    2026      93     3421     3149  Regular    4064
87349    2026      93     3428     3416  Regular    4258
87350    2026      93     3437     3139  Regular    4161
87351    2026      93     3452     3160  Regular    4040
87352    2026      93     3466     3122  Regular    4444

[87353 rows x 6 columns]

In [61]:
w_game_cities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87353 entries, 0 to 87352
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Season   87353 non-null  int64
 1   DayNum   87353 non-null  int64
 2   WTeamID  87353 non-null  int64
 3   LTeamID  87353 non-null  int64
 4   CRType   87353 non-null  object
 5   CityID   87353 non-null  int64
dtypes: int64(5), object(1)
memory usage: 4.0+ MB

In [62]:
m_ordinal = pd.read_csv('/Users/shaurya/Downloads/MMasseyOrdinals.csv')

In [63]:
m_ordinal

         Season  RankingDayNum SystemName  TeamID  OrdinalRank
0          2003             35        SEL    1102          159
1          2003             35        SEL    1103          229
2          2003             35        SEL    1104           12
3          2003             35        SEL    1105          314
4          2003             35        SEL    1106          260
...         ...            ...        ...     ...          ...
5864996    2026            133        WLS    1477          318
5864997    2026            133        WLS    1478          303
5864998    2026            133        WLS    1479          287
5864999    2026            133        WLS    1480          293
5865000    2026            133        WLS    1481          308

[5865001 rows x 5 columns]

In [64]:
m_ordinal.isnull().sum()

Season           0
RankingDayNum    0
SystemName       0
TeamID           0
OrdinalRank      0
dtype: int64

In [65]:
m_team_coach = pd.read_csv('/Users/shaurya/Downloads/MTeamCoaches.csv')

In [66]:
m_team_coach

       Season  TeamID  FirstDayNum  LastDayNum            CoachName
0        1985    1102            0         154        reggie_minton
1        1985    1103            0         154          bob_huggins
2        1985    1104            0         154       wimp_sanderson
3        1985    1106            0         154         james_oliver
4        1985    1108            0         154        davey_whitney
...       ...     ...          ...         ...                  ...
13893    2026    1477            0          93  jaret_von_rosenberg
13894    2026    1478            0          93        nate_champion
13895    2026    1479            0          93         gary_manchel
13896    2026    1480            0          93           dave_moore
13897    2026    1481            0          93         ted_hotaling

[13898 rows x 5 columns]

In [67]:
m_team_coach.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13898 entries, 0 to 13897
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Season       13898 non-null  int64
 1   TeamID       13898 non-null  int64
 2   FirstDayNum  13898 non-null  int64
 3   LastDayNum   13898 non-null  int64
 4   CoachName    13898 non-null  object
dtypes: int64(4), object(1)
memory usage: 543.0+ KB

In [68]:
confrences = pd.read_csv('/Users/shaurya/Downloads/Conferences.csv')

In [69]:
confrences

    ConfAbbrev                                   Description
0        a_sun                       Atlantic Sun Conference
1        a_ten                        Atlantic 10 Conference
2          aac                  American Athletic Conference
3          acc                     Atlantic Coast Conference
4          aec                       America East Conference
5          asc                     American South Conference
6          awc                      American West Conference
7     big_east                           Big East Conference
8    big_eight                          Big Eight Conference
9      big_sky                            Big Sky Conference
10   big_south                          Big South Conference
11     big_ten                            Big Ten Conference
12  big_twelve                             Big 12 Conference
13    big_west                           Big West Conference
14         caa                  Coastal Athletic Association
15        cusa                                Conference USA
16       ecacm  Eastern Collegiate Athletic Conference Metro
17       ecacn  Eastern Collegiate Athletic Conference North
18       ecacs  Eastern Collegiate Athletic Conference South
19         ecc                         East Coast Conference
20        gmwc                      Great Midwest Conference
21         gsc                          Gulf Star Conference
22         gwc                         Great West Conference
23     horizon                                Horizon League
24         ind                                   Independent
25         ivy                                    Ivy League
26        maac            Metro Atlantic Athletic Conference
27         mac                       Mid-American Conference
28        meac               Mid-Eastern Athletic Conference
29       metro   Metropolitan Collegiate Athletic Conference
30    mid_cont                      Mid-Continent Conference
31         mvc                    Missouri Valley Conference
32     mw_city                    Midwestern City Conference
33     mw_coll              Midwestern Collegiate Conference
34         mwc                      Mountain West Conference
35         nac                     North Atlantic Conference
36         nec                          Northeast Conference
37         ovc                        Ohio Valley Conference
38     pac_ten                         Pacific-10 Conference
39  pac_twelve                         Pacific-12 Conference
40     patriot                                Patriot League
41        pcaa            Pacific Coast Athletic Association
42         sec                       Southeastern Conference
43    southern                           Southern Conference
44   southland                          Southland Conference
45      summit                                 Summit League
46    sun_belt                           Sun Belt Conference
47        swac                 Southwest Athletic Conference
48         swc                          Southwest Conference
49         wac                   Western Athletic Conference
50         wcc                         West Coast Conference

In [70]:
confrences.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ConfAbbrev   51 non-null     object
 1   Description  51 non-null     object
dtypes: object(2)
memory usage: 948.0+ bytes

In [71]:
m_team_confrence = pd.read_csv('/Users/shaurya/Downloads/MTeamConferences.csv')

In [72]:
m_team_confrence

       Season  TeamID ConfAbbrev
0        1985    1102        wac
1        1985    1103        ovc
2        1985    1104        sec
3        1985    1106       swac
4        1985    1108       swac
...       ...     ...        ...
13748    2026    1477  southland
13749    2026    1478        nec
13750    2026    1479        nec
13751    2026    1480      a_sun
13752    2026    1481        nec

[13753 rows x 3 columns]

In [73]:
m_team_confrence.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13753 entries, 0 to 13752
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Season      13753 non-null  int64
 1   TeamID      13753 non-null  int64
 2   ConfAbbrev  13753 non-null  object
dtypes: int64(2), object(1)
memory usage: 322.5+ KB

In [74]:
w_team_confrence = pd.read_csv('/Users/shaurya/Downloads/WTeamConferences.csv')

In [75]:
w_team_confrence

      Season  TeamID ConfAbbrev
0       1998    3102        wac
1       1998    3103        mac
2       1998    3104        sec
3       1998    3106       swac
4       1998    3108       swac
...      ...     ...        ...
9848    2026    3477  southland
9849    2026    3478        nec
9850    2026    3479        nec
9851    2026    3480      a_sun
9852    2026    3481        nec

[9853 rows x 3 columns]

In [76]:
w_team_confrence.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9853 entries, 0 to 9852
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Season      9853 non-null   int64
 1   TeamID      9853 non-null   int64
 2   ConfAbbrev  9853 non-null   object
dtypes: int64(2), object(1)
memory usage: 231.1+ KB

In [77]:
m_confrence_tourneygame = pd.read_csv('/Users/shaurya/Downloads/MConferenceTourneyGames.csv')

In [78]:
m_confrence_tourneygame

      Season ConfAbbrev  DayNum  WTeamID  LTeamID
0       2001        ovc     120     1122     1369
1       2001        ovc     120     1183     1287
2       2001        ovc     120     1293     1398
3       2001        ovc     120     1399     1404
4       2001      a_sun     121     1194     1144
...      ...        ...     ...      ...      ...
6788    2025        sec     132     1196     1397
6789    2025        aac     132     1272     1412
6790    2025    big_ten     132     1276     1458
6791    2025      a_ten     132     1433     1206
6792    2025        ivy     132     1463     1165

[6793 rows x 5 columns]

In [79]:
m_confrence_tourneygame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6793 entries, 0 to 6792
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Season      6793 non-null   int64
 1   ConfAbbrev  6793 non-null   object
 2   DayNum      6793 non-null   int64
 3   WTeamID     6793 non-null   int64
 4   LTeamID     6793 non-null   int64
dtypes: int64(4), object(1)
memory usage: 265.5+ KB

In [80]:
w_confrence_tourneygame = pd.read_csv('/Users/shaurya/Downloads/WConferenceTourneyGames.csv')

In [81]:
w_confrence_tourneygame

      Season ConfAbbrev  DayNum  WTeamID  LTeamID
0       2002        ovc     120     3122     3369
1       2002        ovc     120     3184     3293
2       2002        ovc     120     3287     3404
3       2002        ovc     120     3399     3183
4       2002    horizon     121     3139     3460
...      ...        ...     ...      ...      ...
6476    2025   big_west     131     3471     3413
6477    2025        nec     132     3192     3476
6478    2025    patriot     132     3250     3119
6479    2025        mvc     132     3293     3125
6480    2025        caa     132     3456     3144

[6481 rows x 5 columns]

In [82]:
w_confrence_tourneygame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6481 entries, 0 to 6480
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Season      6481 non-null   int64
 1   ConfAbbrev  6481 non-null   object
 2   DayNum      6481 non-null   int64
 3   WTeamID     6481 non-null   int64
 4   LTeamID     6481 non-null   int64
dtypes: int64(4), object(1)
memory usage: 253.3+ KB

In [83]:
m_secondary_toruney_team = pd.read_csv('/Users/shaurya/Downloads/MSecondaryTourneyTeams.csv')

In [84]:
m_secondary_toruney_team

      Season SecondaryTourney  TeamID
0       1985              NIT    1108
1       1985              NIT    1133
2       1985              NIT    1139
3       1985              NIT    1145
4       1985              NIT    1151
...      ...              ...     ...
1890    2025              NIT    1414
1891    2025              NIT    1415
1892    2025              NIT    1430
1893    2025              NIT    1455
1894    2025              NIT    1466

[1895 rows x 3 columns]

In [85]:
m_secondary_toruney_team.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1895 entries, 0 to 1894
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Season            1895 non-null   int64
 1   SecondaryTourney  1895 non-null   object
 2   TeamID            1895 non-null   int64
dtypes: int64(2), object(1)
memory usage: 44.5+ KB

In [86]:
w_secondary_toruney_team = pd.read_csv('/Users/shaurya/Downloads/WSecondaryTourneyTeams.csv')

In [87]:
w_secondary_toruney_team

     Season SecondaryTourney  TeamID
0      2013             WNIT    3103
1      2013             WNIT    3111
2      2013             WNIT    3114
3      2013             WNIT    3116
4      2013             WNIT    3119
..      ...              ...     ...
899    2025             WBIT    3461
900    2025             WNIT    3470
901    2025             WNIT    3473
902    2025             WNIT    3475
903    2025             WNIT    3476

[904 rows x 3 columns]

In [88]:
w_secondary_toruney_team.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 904 entries, 0 to 903
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Season            904 non-null    int64
 1   SecondaryTourney  904 non-null    object
 2   TeamID            904 non-null    int64
dtypes: int64(2), object(1)
memory usage: 21.3+ KB

In [89]:
m_sec_tour_compact_res = pd.read_csv('/Users/shaurya/Downloads/MSecondaryTourneyCompactResults.csv')

In [90]:
m_sec_tour_compact_res

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,SecondaryTourney
0,1985,136,1151,67,1155,65,H,0,NIT
1,1985,136,1153,77,1245,61,H,0,NIT
2,1985,136,1201,79,1365,76,H,0,NIT
3,1985,136,1231,79,1139,57,H,0,NIT
4,1985,136,1249,78,1222,71,H,0,NIT
...,...,...,...,...,...,...,...,...,...
1860,2025,150,1416,88,1153,80,N,0,CBC
1861,2025,150,1437,60,1425,59,N,0,CBC
1862,2025,152,1304,79,1129,69,N,0,CBC
1863,2025,152,1416,104,1437,98,N,1,CBC
1864,2025,153,1304,77,1416,66,N,0,CBC

In [91]:
m_sec_tour_compact_res.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1865 entries, 0 to 1864
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Season            1865 non-null   int64
 1   DayNum            1865 non-null   int64
 2   WTeamID           1865 non-null   int64
 3   WScore            1865 non-null   int64
 4   LTeamID           1865 non-null   int64
 5   LScore            1865 non-null   int64
 6   WLoc              1865 non-null   object
 7   NumOT             1865 non-null   int64
 8   SecondaryTourney  1865 non-null   object
dtypes: int64(7), object(2)
memory usage: 131.3+ KB

In [92]:
w_sec_tour_compact_res = pd.read_csv('/Users/shaurya/Downloads/WSecondaryTourneyCompactResults.csv')

In [93]:
w_sec_tour_compact_res

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,SecondaryTourney
0,2013,135,3120,80,3412,57,H,0,WNIT
1,2013,135,3140,69,3226,54,H,0,WNIT
2,2013,135,3158,72,3297,70,A,0,WBI
3,2013,135,3183,60,3281,58,A,0,WNIT
4,2013,135,3189,68,3184,61,H,0,WBI
...,...,...,...,...,...,...,...,...,...
901,2025,147,3407,97,3295,88,A,1,WNIT
902,2025,149,3138,74,3156,69,H,0,WNIT
903,2025,149,3278,75,3125,63,N,0,WBIT
904,2025,149,3407,99,3229,96,A,0,WNIT
905,2025,152,3138,88,3407,84,H,0,WNIT

In [94]:
w_sec_tour_compact_res.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 906 entries, 0 to 905
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Season            906 non-null    int64
 1   DayNum            906 non-null    int64
 2   WTeamID           906 non-null    int64
 3   WScore            906 non-null    int64
 4   LTeamID           906 non-null    int64
 5   LScore            906 non-null    int64
 6   WLoc              906 non-null    object
 7   NumOT             906 non-null    int64
 8   SecondaryTourney  906 non-null    object
dtypes: int64(7), object(2)
memory usage: 63.8+ KB

In [95]:
m_team_spelling = pd.read_csv('/Users/shaurya/Downloads/MTeamSpellings.csv')

In [96]:
m_team_spelling

        TeamNameSpelling  TeamID
0       a&m-corpus chris    1394
1     a&m-corpus christi    1394
2            abilene chr    1101
3      abilene christian    1101
4      abilene-christian    1101
...                  ...     ...
1173       youngstown st    1464
1174      youngstown st.    1464
1175    youngstown state    1464
1176       youngstown-st    1464
1177    youngstown-state    1464

[1178 rows x 2 columns]

In [97]:
m_team_spelling.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1178 entries, 0 to 1177
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   TeamNameSpelling  1178 non-null   object
 1   TeamID            1178 non-null   int64
dtypes: int64(1), object(1)
memory usage: 18.5+ KB

In [98]:
w_team_spelling = pd.read_csv('/Users/shaurya/Downloads/WTeamSpellings.csv')

In [99]:
w_team_spelling

        TeamNameSpelling  TeamID
0       a&m-corpus chris    3394
1     a&m-corpus christi    3394
2            abilene chr    3101
3      abilene christian    3101
4      abilene-christian    3101
...                  ...     ...
1166       youngstown st    3464
1167      youngstown st.    3464
1168    youngstown state    3464
1169       youngstown-st    3464
1170    youngstown-state    3464

[1171 rows x 2 columns]

In [100]:
w_team_spelling.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1171 entries, 0 to 1170
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   TeamNameSpelling  1171 non-null   object
 1   TeamID            1171 non-null   int64
dtypes: int64(1), object(1)
memory usage: 18.4+ KB

In [101]:
m_tourney_slot = pd.read_csv('/Users/shaurya/Downloads/MNCAATourneySlots.csv')

In [102]:
m_tourney_slot

      Season  Slot StrongSeed WeakSeed
0       1985  R1W1        W01      W16
1       1985  R1W2        W02      W15
2       1985  R1W3        W03      W14
3       1985  R1W4        W04      W13
4       1985  R1W5        W05      W12
...      ...   ...        ...      ...
2581    2025  R6CH       R5WX     R5YZ
2582    2025   W16       W16a     W16b
2583    2025   X11       X11a     X11b
2584    2025   Y11       Y11a     Y11b
2585    2025   Y16       Y16a     Y16b

[2586 rows x 4 columns]

In [103]:
m_tourney_slot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2586 entries, 0 to 2585
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Season      2586 non-null   int64
 1   Slot        2586 non-null   object
 2   StrongSeed  2586 non-null   object
 3   WeakSeed    2586 non-null   object
dtypes: int64(1), object(3)
memory usage: 80.9+ KB

In [104]:
w_tourney_slot = pd.read_csv('/Users/shaurya/Downloads/WNCAATourneySlots.csv')

In [105]:
w_tourney_slot

      Season  Slot StrongSeed WeakSeed
0       1998  R1W1        W01      W16
1       1998  R1W2        W02      W15
2       1998  R1W3        W03      W14
3       1998  R1W4        W04      W13
4       1998  R1W5        W05      W12
...      ...   ...        ...      ...
1775    2025  R6CH       R5WX     R5YZ
1776    2025   W11       W11a     W11b
1777    2025   X11       X11a     X11b
1778    2025   X16       X16a     X16b
1779    2025   Y16       Y16a     Y16b

[1780 rows x 4 columns]

In [106]:
w_tourney_slot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1780 entries, 0 to 1779
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Season      1780 non-null   int64
 1   Slot        1780 non-null   object
 2   StrongSeed  1780 non-null   object
 3   WeakSeed    1780 non-null   object
dtypes: int64(1), object(3)
memory usage: 55.8+ KB

In [107]:
m_tourney_seed_roundslot = pd.read_csv('/Users/shaurya/Downloads/MNCAATourneySeedRoundSlots.csv')

In [108]:
m_tourney_seed_roundslot

     Seed  GameRound GameSlot  EarlyDayNum  LateDayNum
0     W01          1     R1W1          136         137
1     W01          2     R2W1          138         139
2     W01          3     R3W1          143         144
3     W01          4     R4W1          145         146
4     W01          5     R5WX          152         152
..    ...        ...      ...          ...         ...
771  Z16b          2     R2Z1          138         139
772  Z16b          3     R3Z1          143         144
773  Z16b          4     R4Z1          145         146
774  Z16b          5     R5YZ          152         152
775  Z16b          6     R6CH          154         154

[776 rows x 5 columns]

In [109]:
m_tourney_seed_roundslot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 776 entries, 0 to 775
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Seed         776 non-null    object
 1   GameRound    776 non-null    int64
 2   GameSlot     776 non-null    object
 3   EarlyDayNum  776 non-null    int64
 4   LateDayNum   776 non-null    int64
dtypes: int64(3), object(2)
memory usage: 30.4+ KB

In [110]:
m_regular_season_detailed.columns

Index(['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc',
       'NumOT', 'WFGM', 'WFGA', 'WFGM3', 'WFGA3', 'WFTM', 'WFTA', 'WOR', 'WDR',
       'WAst', 'WTO', 'WStl', 'WBlk', 'WPF', 'LFGM', 'LFGA', 'LFGM3', 'LFGA3',
       'LFTM', 'LFTA', 'LOR', 'LDR', 'LAst', 'LTO', 'LStl', 'LBlk', 'LPF'],
      dtype='object')